import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "en" | "zh";

const TEXT = {
  en: {
    appName: "Request & Report",
    home: "Home",
    requests: "Requests",
    reports: "Reports",
    house: "House",
    signedOut: "Signed out",
    account: "Account",
    checkingAccount: "Checking account...",
    signInUnavailable: "Sign-in is unavailable in this build.",
    actionFailed: "Something went wrong.",
    signingOut: "Signing out...",
    signOut: "Sign out",
    openingGoogle: "Opening Google...",
    signInWithGoogle: "Sign in with Google",
    signingIn: "Signing in...",
    continueAsGuest: "Continue as guest",
    guestUser: "Guest user",
    createOrJoinHome: "Create or join one shared home",
    signInToCreateHome: "Sign in to create or join a home",
    displayName: "Display name",
    saveName: "Save name",
    save: "Save",
    homeNameSaved: "Home name saved.",
    couldNotSaveHomeName: "Could not save home name.",
    removeMember: "Remove member",
    confirmRemoveMember: "Remove {name} from this home?",
    memberRemoved: "Member removed.",
    couldNotRemoveMember: "Could not remove member.",
    startHome: "Start a home",
    startHomeHint: "Create one home, or join with an invite code.",
    homeName: "Home name",
    createHome: "Create home",
    inviteCode: "Invite code",
    join: "Join",
    joinAnotherHome: "Join another home",
    copy: "Copy",
    members: "Members",
    owner: "Owner",
    member: "Member",
    working: "Working...",
    productLinkOptional: "Product link optional",
    description: "Description",
    price: "Price",
    submitRequest: "Submit request",
    submitReport: "Submit report",
    pending: "Pending",
    all: "All",
    mine: "Mine",
    open: "Open",
    activeMemorials: "Needs review",
    resolvedMemorials: "Reviewed",
    weeklySummary: "Weekly summary",
    weeklySummaryEmpty: "No reports received this week",
    chooseMember: "Choose member",
    comments: "Comments",
    requestExpiry: "Requests expire after 30 days",
    reportExpiry: "Reports expire after 30 days",
    createRequest: "Create request",
    createReport: "Create report",
    requestNamePlaceholder: "What do you want to buy?",
    submitting: "Submitting...",
    noRequestsTitle: "No requests here",
    noRequestsDescription: "Requests will show up after someone submits one.",
    noReportsTitle: "No reports here",
    noReportsDescription: "Reports will show up after someone files one.",
    requestNotFound: "Request not found",
    reportNotFound: "Report not found",
    requestNotFoundDescription: "We couldn't find that request.",
    reportNotFoundDescription: "We couldn't find that report.",
    backToRequests: "Back to requests",
    backToReports: "Back to reports",
    requestedBy: "Requested by {name}",
    reportedBy: "Reported by {name}",
    byUser: "By {name}",
    clearsAfter: "Clears after",
    clears: "Clears {date}",
    viewProductLink: "View product link",
    productLink: "Product link",
    copyProductLink: "Copy link",
    openProductLink: "Open link",
    copiedProductLink: "Link copied.",
    approvalProgress: "{positive} {positiveLabel} · {negative} {negativeLabel} · reviewed {totalVotes}/{totalVoters}",
    cardVoteSummary: "{positiveLabel} {positive} votes · reviewed {totalVotes}/{totalVoters}",
    latestVote: "Latest vote",
    noVoteDetails: "No votes yet.",
    requesterVoteHint: "You can track status here. Other members vote.",
    voteHint: "Add or update your comment with your vote.",
    changeVoteHint: "You already reviewed this. You can update your vote.",
    commentOptional: "Comment optional",
    currentChoice: "Current choice",
    reportTitle: "Report {name}",
    currentUser: "You",
    receivedReportsCount: "{count} received",
    copiedInviteCode: "Invite code copied.",
    homeCreated: "Home created. Share the invite code with your members.",
    couldNotCreateHome: "Could not create home.",
    joinedHome: "Joined home.",
    couldNotJoinHome: "Could not join home.",
    nameSaved: "Name saved.",
    couldNotSaveName: "Could not save name.",
    primaryNavigation: "Primary",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    statusOpen: "Open",
    statusAgreed: "Agreed",
    statusDisagreed: "Disagreed",
    statusExpired: "Expired",
    noHomeRequest: "Sign in, then create or join a home before submitting requests.",
    noHomeReport: "Sign in, then create or join a home before submitting reports.",
    permissionsHint: "If you see Missing or insufficient permissions, deploy the included Firestore rules.",
    delete: "Delete",
    deleteRequest: "Delete request",
    deleteReport: "Delete report",
    confirmDeleteRequest: "Delete this request?",
    confirmDeleteReport: "Delete this report?",
    couldNotDeleteRequest: "Could not delete request.",
    couldNotDeleteReport: "Could not delete report.",
    targetResponse: "Reported member response",
    targetResponsePlaceholder: "Add your response here",
    saveResponse: "Save response",
    responseSaved: "Response saved.",
    couldNotSaveResponse: "Could not save response.",
    reviewMemorial: "Review",
    approveAction: "Approve",
    rejectAction: "Reject",
    agreeAction: "Agree",
    disagreeAction: "Disagree",
    approvalRate: "Approval rate",
    approvalRateHint: "How often each member approves or agrees with other members' posts.",
    noVotesYet: "No votes yet",
    needsVotes: "needs {required} of {total}",
    noHomeJoined: "No home joined",
    demoHome: "Demo home",
    pendingFromYou: "{pending} pending · {mine} from you",
    openReportsThisWeek: "{count} open this week",
    inviteAndMembers: "invite and members",
    signedInAs: "{count} members · signed in as {name}",
    notificationTitle: "New update",
    notificationBody: "Someone in your house made an update. Open the app to check.",
    enableNotifications: "Enable notifications",
    notificationsOn: "Notifications on",
    notificationsBlocked: "Notifications blocked in browser settings",
  },
  zh: {
    appName: "有本要奏",
    home: "首页",
    requests: "臣要上奏",
    reports: "臣要告发",
    house: "小朝廷",
    signedOut: "未登录",
    account: "个人账号",
    checkingAccount: "正在检查账号...",
    signInUnavailable: "当前版本暂不支持登录。",
    actionFailed: "操作失败，请稍后再试。",
    signingOut: "正在退出...",
    signOut: "退出登录",
    openingGoogle: "正在打开 Google...",
    signInWithGoogle: "用 Google 登录",
    signingIn: "正在登录...",
    continueAsGuest: "游客进入",
    guestUser: "游客",
    createOrJoinHome: "创建或加入一个小朝廷",
    signInToCreateHome: "请先登录，再创建或加入小朝廷",
    displayName: "用户名",
    saveName: "保存用户名",
    save: "保存",
    homeNameSaved: "小朝廷名称已保存。",
    couldNotSaveHomeName: "无法保存小朝廷名称。",
    removeMember: "移除同僚",
    confirmRemoveMember: "确定要把 {name} 移出这个小朝廷吗？",
    memberRemoved: "同僚已移除。",
    couldNotRemoveMember: "无法移除同僚。",
    startHome: "创建小朝廷",
    startHomeHint: "创建一个小朝廷，或使用邀请码加入。",
    homeName: "小朝廷名称",
    createHome: "创建小朝廷",
    inviteCode: "邀请码",
    join: "加入",
    joinAnotherHome: "加入另一个小朝廷",
    copy: "复制",
    members: "同僚",
    owner: "管理员",
    member: "同僚",
    working: "处理中...",
    productLinkOptional: "商品链接可选",
    description: "描述",
    price: "价格",
    submitRequest: "提交申请",
    submitReport: "提交举报",
    pending: "待处理",
    all: "全部",
    mine: "我的",
    open: "进行中",
    activeMemorials: "待批折子",
    resolvedMemorials: "已批折子",
    weeklySummary: "本周案情",
    weeklySummaryEmpty: "本周暂无案情",
    chooseMember: "选择同僚",
    comments: "说明",
    requestExpiry: "折子会在 30 天后清理",
    reportExpiry: "案情会在 30 天后清理",
    createRequest: "提交上奏",
    createReport: "提交告发",
    requestNamePlaceholder: "想买什么？",
    submitting: "提交中...",
    noRequestsTitle: "暂无折子",
    noRequestsDescription: "有人提交后会显示在这里。",
    noReportsTitle: "暂无案情",
    noReportsDescription: "有人告发后会显示在这里。",
    requestNotFound: "没有找到这个折子",
    reportNotFound: "没有找到这个案情",
    requestNotFoundDescription: "这个折子可能已经被清理了。",
    reportNotFoundDescription: "这个案情可能已经被清理了。",
    backToRequests: "返回上奏",
    backToReports: "返回告发",
    requestedBy: "{name} 上奏",
    reportedBy: "{name} 告发",
    byUser: "{name} 提交",
    clearsAfter: "清理时间",
    clears: "{date} 清理",
    viewProductLink: "查看商品链接",
    productLink: "商品链接",
    copyProductLink: "复制链接",
    openProductLink: "打开链接",
    copiedProductLink: "链接已复制。",
    approvalProgress: "{positive} {positiveLabel} · {negative} {negativeLabel} · 已批 {totalVotes}/{totalVoters}",
    cardVoteSummary: "{positiveLabel} {positive} 票 · 已批 {totalVotes}/{totalVoters}",
    latestVote: "最新批复",
    noVoteDetails: "还没有人批折子。",
    requesterVoteHint: "你可以在这里查看状态，其他同僚会来批折子。",
    voteHint: "可以附上批复说明。",
    changeVoteHint: "你已经批过，可以修改批复。",
    commentOptional: "批复说明可选",
    currentChoice: "当前选择",
    reportTitle: "告发 {name}",
    currentUser: "你",
    receivedReportsCount: "收到 {count} 件",
    copiedInviteCode: "邀请码已复制。",
    homeCreated: "小朝廷已创建，可以把邀请码分享给同僚。",
    couldNotCreateHome: "无法创建小朝廷。",
    joinedHome: "已加入小朝廷。",
    couldNotJoinHome: "无法加入小朝廷。",
    nameSaved: "用户名已保存。",
    couldNotSaveName: "无法保存用户名。",
    primaryNavigation: "主导航",
    statusPending: "待批",
    statusApproved: "已准奏",
    statusRejected: "已驳回",
    statusOpen: "进行中",
    statusAgreed: "已同意",
    statusDisagreed: "已不同意",
    statusExpired: "已过期",
    noHomeRequest: "请先登录并创建或加入小朝廷，再提交申请。",
    noHomeReport: "请先登录并创建或加入小朝廷，再提交举报。",
    permissionsHint: "如果看到 Missing or insufficient permissions，请部署项目里的 Firestore 规则。",
    delete: "删除",
    deleteRequest: "删除申请",
    deleteReport: "删除举报",
    confirmDeleteRequest: "确定要删除这个申请吗？",
    confirmDeleteReport: "确定要删除这个举报吗？",
    couldNotDeleteRequest: "无法删除申请。",
    couldNotDeleteReport: "无法删除举报。",
    targetResponse: "被举报人申辩",
    targetResponsePlaceholder: "在这里写你的申辩说明",
    saveResponse: "保存申辩",
    responseSaved: "申辩已保存。",
    couldNotSaveResponse: "无法保存申辩。",
    reviewMemorial: "批折子",
    approveAction: "准奏",
    rejectAction: "驳回",
    agreeAction: "同意",
    disagreeAction: "不同意",
    approvalRate: "准奏率",
    approvalRateHint: "每个人给别人投票时，选择通过/同意的比例。",
    noVotesYet: "暂无投票",
    needsVotes: "需要 {required}/{total}",
    noHomeJoined: "还没有加入小朝廷",
    demoHome: "有本要奏 Demo",
    pendingFromYou: "{pending} 个待批 · 你提交了 {mine} 个",
    openReportsThisWeek: "本周 {count} 个进行中",
    inviteAndMembers: "邀请码和同僚",
    signedInAs: "{count} 位同僚 · 当前用户 {name}",
    notificationTitle: "小朝廷有新动静",
    notificationBody: "有人提交或批了新内容，打开有本要奏看看。",
    enableNotifications: "开启通知",
    notificationsOn: "通知已开启",
    notificationsBlocked: "通知已被浏览器阻止",
  },
} as const;

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof typeof TEXT.en) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    return localStorage.getItem("shared-home-language") === "en" ? "en" : "zh";
  });

  useEffect(() => {
    document.title = TEXT[language].appName;
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => {
    return {
      language,
      setLanguage: (nextLanguage) => {
        localStorage.setItem("shared-home-language", nextLanguage);
        setLanguageState(nextLanguage);
      },
      t: (key) => TEXT[language][key],
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
